//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resistencia.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pages
    {
        public Nullable<int> ID_Visual { get; set; }
        public int ID_Portfolio { get; set; }
        public string Contenido { get; set; }
        public int ID { get; set; }
    
        public virtual Portfolio Portfolio { get; set; }
        public virtual Visual Visual { get; set; }
    }
}
