//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DataTransferObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTOProyecto_categorias
    {
        public string Categoria { get; set; }
        public string Titulo_proyecto { get; set; }
        public int ID { get; set; }
    
        public DTOCategoria Categoria1 { get; set; }
        public DTOProyecto Proyecto { get; set; }
    }
}
