//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DataTransferObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTOUsuarios
    {
        public DTOUsuarios()
        {
            this.Comentarios = new HashSet<DTOComentarios>();
            this.Enviados = new HashSet<DTOMensajes>();
            this.Recibidos = new HashSet<DTOMensajes>();
            this.Proyecto = new HashSet<DTOProyecto>();
            this.Seguidos = new HashSet<DTOUsuarios>();
            this.Seguidores = new HashSet<DTOUsuarios>();
            this.Proyecto1 = new HashSet<DTOProyecto>();
        }
    
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Descripcion { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Ciudad { get; set; }
        public string Pais { get; set; }
        public string Profesion { get; set; }
        public System.DateTime Fecha_nac { get; set; }
        public string Empresa { get; set; }
        public string URL { get; set; }
        public Nullable<int> ID_Visual { get; set; }
    
        public  ICollection<DTOComentarios> Comentarios { get; set; }
        public  ICollection<DTOMensajes> Enviados { get; set; }
        public  ICollection<DTOMensajes> Recibidos { get; set; }
        public  ICollection<DTOProyecto> Proyecto { get; set; }
        public  ICollection<DTOUsuarios> Seguidos { get; set; }
        public  ICollection<DTOUsuarios> Seguidores { get; set; }
        public  ICollection<DTOProyecto> Proyecto1 { get; set; }
    }
}
