//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesLogic.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;

    public class Categoria
    {
        public Categoria()
        {
            this.Proyecto_categorias = new HashSet<Proyecto_categorias>();
        }
    
        private string Nombre { get; set; }
    
        private ICollection<Proyecto_categorias> Proyecto_categorias { get; set; }
    }
}
