//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public class Comentarios
    {
        private int ID { get; set; }
        private System.DateTime Fecha { get; set; }
        private string Cuerpo { get; set; }
        private string Usuario { get; set; }
        private string Proyecto { get; set; }
    
        private Proyecto Proyecto1 { get; set; }
        private Usuarios Usuarios { get; set; }
    }
}
