//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public class Etiquetas
    {
        private string Titulo_proyecto { get; set; }
        private string Etiquetas1 { get; set; }
        private int ID { get; set; }
    
        private Proyecto Proyecto { get; set; }
    }
}
