//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public class Pages
    {
        private int ID_Visual { get; set; }
        private int ID_Portfolio { get; set; }
        private string Contenido { get; set; }
        private int ID { get; set; }
    
        private Portfolio Portfolio { get; set; }
    }
}
