//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public class Portfolio
    {
        public Portfolio()
        {
            this.Pages = new HashSet<Pages>();
            this.Proyecto1 = new HashSet<Proyecto>();
        }
    
        private int ID { get; set; }
        private string Titulo_Proyecto { get; set; }
    
        private ICollection<Pages> Pages { get; set; }
        private Proyecto Proyecto { get; set; }
        private ICollection<Proyecto> Proyecto1 { get; set; }
    }
}
