//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public class Usuarios
    {
        public Usuarios()
        {
            this.Comentarios = new HashSet<Comentarios>();
            this.Enviados = new HashSet<Mensajes>();
            this.Recibidos = new HashSet<Mensajes>();
            this.Proyectos = new HashSet<Proyecto>();
            this.Seguidores = new HashSet<Usuarios>();
            this.Seguidos = new HashSet<Usuarios>();
            this.Valorados = new HashSet<Proyecto>();
        }

        private string Nombre { get; set; }
        private string Apellido { get; set; }
        private string Descripcion { get; set; }
        private string Email { get; set; }
        private string Password { get; set; }
        private string Ciudad { get; set; }
        private string Pais { get; set; }
        private string Profesion { get; set; }
        private System.DateTime Fecha_nac { get; set; }
        private string Empresa { get; set; }
        private string URL { get; set; }
        private int ID_Visual { get; set; }
    
        private ICollection<Comentarios> Comentarios { get; set; }
        private ICollection<Mensajes> Enviados { get; set; }
        private ICollection<Mensajes> Recibidos { get; set; }
        private ICollection<Proyecto> Proyectos { get; set; }
        private ICollection<Usuarios> Seguidores { get; set; }
        private ICollection<Usuarios> Seguidos { get; set; }
        private ICollection<Proyecto> Valorados { get; set; }
    }
}
